# Generated by Django 4.2.27 on 2025-12-30 03:40

import apps.core.validators
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        db_index=True,
                        help_text="ID karyawan unik (contoh: EMP0001, EMP0002)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Nomor telepon karyawan (08xxx atau 62xxx)",
                        max_length=15,
                        validators=[apps.core.validators.validate_phone_number],
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(
                        blank=True, help_text="Tanggal mulai bekerja", null=True
                    ),
                ),
                (
                    "type_of_employment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                        ],
                        help_text="Jenis kepegawaian",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("on_leave", "On Leave"),
                            ("terminated", "Terminated"),
                        ],
                        db_index=True,
                        default="active",
                        help_text="Status kepegawaian",
                        max_length=20,
                    ),
                ),
                (
                    "face_photo_front",
                    models.ImageField(
                        blank=True,
                        help_text="Foto wajah tampak depan",
                        null=True,
                        upload_to="faces/front/%Y/%m/",
                    ),
                ),
                (
                    "face_photo_left",
                    models.ImageField(
                        blank=True,
                        help_text="Foto wajah tampak kiri",
                        null=True,
                        upload_to="faces/left/%Y/%m/",
                    ),
                ),
                (
                    "face_photo_right",
                    models.ImageField(
                        blank=True,
                        help_text="Foto wajah tampak kanan",
                        null=True,
                        upload_to="faces/right/%Y/%m/",
                    ),
                ),
                (
                    "face_encoding",
                    models.JSONField(
                        blank=True,
                        editable=False,
                        help_text="Face encoding data untuk face recognition (auto-generated)",
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Soft delete timestamp", null=True
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "ordering": ["employee_id"],
                "permissions": [
                    ("view_all_employees", "Can view all employees"),
                    ("view_division_employees", "Can view division employees only"),
                    ("manage_employee_face_data", "Can manage face recognition data"),
                    ("bulk_import_employees", "Can bulk import employees"),
                    ("export_employee_data", "Can export employee data"),
                    ("reset_employee_password", "Can reset employee password"),
                ],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nama divisi (HR Department, HR Manager, HR Recruitment)",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Kode unik divisi (HR, HR-MGR, HR-RECRUIT)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Deskripsi divisi"),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Hierarchy level (0=top, 1=sub, 2=child, dst)",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent division (kosong jika top level)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="accounts.division",
                    ),
                ),
            ],
            options={
                "verbose_name": "Division",
                "verbose_name_plural": "Divisions",
                "db_table": "divisions",
                "ordering": ["level", "code"],
                "unique_together": {("name", "parent")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="division",
            field=models.ForeignKey(
                blank=True,
                help_text="Divisi karyawan",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="accounts.division",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["employee_id"], name="idx_employee_id"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["status", "is_active"], name="idx_status_active"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["division", "is_active"], name="idx_division_active"
            ),
        ),
    ]
