# Generated by Django 4.2.27 on 2025-12-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Permission",
                "verbose_name_plural": "Application Permissions",
                "permissions": [
                    ("view_company_dashboard", "Can view company-wide dashboard"),
                    ("view_division_dashboard", "Can view division dashboard"),
                    ("view_own_dashboard", "Can view own dashboard only"),
                    ("export_dashboard_data", "Can export dashboard data"),
                    ("approve_attendance", "Can approve attendance exceptions"),
                    ("view_all_attendance_report", "Can view all attendance reports"),
                    ("approve_all_leaves", "Can approve all leave requests"),
                    ("reject_leave", "Can reject leave requests"),
                    ("cancel_approved_leave", "Can cancel approved leaves"),
                    ("export_attendance_report", "Can export attendance report"),
                    ("export_leave_report", "Can export leave report"),
                    ("export_payroll_report", "Can export payroll report"),
                    ("view_analytics", "Can view analytics dashboard"),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
